# Server parameters go in the SERVER section.
[SERVER]
base_url: <full url goes here>
# The URL should be the same as you see in your browser,
# i.e. if it's on a non-default port, write it into the URL
# the usual way.

# Login information:
username: user
# Use triple quotes here, especially if your password contains any
# special characters.
password: """SekritPasswird"""

# This option explicitly sets the number of simultaneous download/transcoding
# operations that will be executed. By default, the value is equal to the number
# of cores in the machine running pseudosonic-go. You may want to tune it
# so as to not overwhelm your server or bump into simultaneous transcode
# limits as introduced in recent versions of Navidrome.
#workers: 16

# Named sections other than SERVER describe a download profile.
# You can have multiple. If you don't give one on the command line,
# all of them will be executed by default.

[phone]

#default: no
# If this profile is not meant to be processed by default, uncomment this.
# Then, you will only be able to invoke it by name on command line.

#playlist: foo
# By default, the source of songs for the profile is the logged in
# user's favorites.
# You can download the songs belonging to a given playlist instead,
# for which you put the name of the playlist in this variable.

#overwrite: yes
# Whether to overwrite a file if a downloaded one already exists.
# Defaults to no -- in which case the file is skipped.

coverart: yes
# Whether to download cover art into album directories.
# Defaults to no.
#
# When transcoding, this is usually unnecessary, since
# ffmpeg will embed cover art during transcoding, even if your
# source files do not have embedded cover art. (If you use Picard
# or Beet, they usually do.) But whether that works with, e.g.,
# opus encoding target, depends on the version of ffmpeg you have.
#
# Some players may also ignore embedded cover art, but support
# in-directory cover art, so select accordingly.

#coverart_size: 512
# The default is 512.

#coverart_file: cover.jpg
# The default is cover.jpg.
# Cover art will be converted into the format specified by the
# file extension. jpg, png, webp and bmp are supported.

#coverart_square: no
# Whether the cover art image will be coerced to square,
# by filling in empty spaces after resizing.
# Some players have problems with non-square images. Default is no.

# Where the downloaded files go. Preferably a full path.
# If it does not exist, the path will be created.
music_dir: phone

flatten: no
# The default value is 'no'.
# When not flattened, downloaded files are saved as a directory tree,
# according to their tags:
#
# <album artist>/<album>/<disc>-<track> <song name>.<format extension>
#
# When, e.g., downloading a playlist, this may not be what you
# want, especially with dumber target players. When this option is
# set, the directory tree becomes
#
# <index number> <song name>.<format extension>
#
# instead, thus allowing you to force files to play in a specific
# order purely through naming them.
# 
# Be aware: 
#
# 1. In general, this feature is only actually useful for playlists.
#    Nothing actually stops you from using it for favorites, but
#    when processing favorites, the results will be in the order
#    the server returns them, which is not guaranteed to be stable.
#    You can end up with the same song appearing multiple times
#    under different index numbers, e.g., when you favorite a new song. 
#
# 2. Per-album cover images are not saved when flattening, as there
#    are no per-album directories. Favorites, likewise, have no cover
#    image to save. The cover image for the playlist as a whole will
#    be saved, but that will be whatever the server returns.

# The desired format and bitrate for when the transcoding
# will happen. On consumer hardware, opus 128 is transparent.
format: opus
bitrate: 128

# Whether transcoding happens at all depends on the value of
# max_bitrate, which defaults to 0.
# If max_bitrate is 0, files will always be transcoded, even when
# this is probably a bad idea.
# If max_bitrate is greater than 0, files which are in one of the
# supported_formats will be downloaded as is, instead of transcoded,
# but only if their bitrate does not exceed max bitrate,
# otherwise they will be transcoded anyway.
# The notion of bitrate also applies to lossless,
# so you can set it high enough that none or only some of them
# trip this check.

max_bitrate: 160
supported_formats: mp3,aac,m4a,ogg,opus,wma,mpc,flac,ape,wv,tta

# Due to how bitrates are calculated on variable bitrate files,
# you want to have max_bitrate slightly higher than the actual maximum
# you wish to have your collection in.

lrc_lyrics: text
# Write out lrc/txt lyrics files if the server supports the requisite
# OpenSubsonic extension and has lyrics for a particular song.
# These go into the file with the same name and location as the
# song and have an .lrc extension.
#
# "no"        - Don't write lyrics files at all. This is the default.
# 
# Any other value implies that a lyrics file will be written
# if the server can return lyrics and has them available.
#
# Different values of this parameter describe what to do when
# the server returns unsynced lyrics:
#
# "flat"  - write out the usual LRC format with time for every
#           line equal to 0.
# "omit"      - only write the file if synced lyrics are available.
# "text"      - write out unsynced lyrics as plain text,
#               with no time markers, but in files with a
#               LRC extension.
# "text.txt"  - same as "text", but plain text lyric filenames
#               also have a TXT extension.
#
# Be aware that Navidrome in particular returns unsynced lyrics
# without empty lines between paragraphs.
#
# Since this example has Poweramp on Android in mind, "text"
# is the appropriate value - Poweramp doesn't display "flat"
# lyrics very well.

#### Here is an example profile for a 
# FIIO Snowsky Echo, audiophile mode,
# i.e. keep as much quality as possible,
# but transcode the songs that the Echo can't play.
[player]

default: no

music_dir: player

# When you have to transcode music at all, ogg is the best
# non-lossless target FIIO Echo supports, and 256 kbit is the
# bitrate at which it should be transparent for anything
# but classical. If you play a lot of classical,
# bump it to 320.
# If you're a true blue audiophile who can
# hear the difference, you don't need this program.
# You can transcode to flac, however, on lossy sources this
# is not worth the space, and with lossless sources you should
# have things in flac already.
format: ogg
bitrate: 256

# The list of supported formats for FIIO Echo is not very long.
# Mind you, I'm not even sure whether Navidrome supports dsf/dff.
# wav and aiff are not included because hopefully you
# don't do something quite so silly with your library.
# aiff is not supported according to faq, and wav
# is actually a container format for a thousand possible
# PCM codecs.
supported_formats: mp3,m4a,ogg,flac,ape,wma,dsf,dff

# Lossless music tends to have a stable average bitrate.
# flac, unless you encode them for bats, will typically not
# exceed a bitrate of 1500. alac m4a tends to hover around
# 2300. Keeping the max bitrate above this number ensures
# that anything FIIO Echo can play at all will be downloaded
# as is, while everything it can't play will become ogg 256.
# For a different player, e.g. with limited storage,
# you might want to bring this number down.
max_bitrate: 2500

# For Echo, the recommended coverart format is like so:
coverart: yes
coverart_file: cover.jpg
coverart_square: yes
coverart_size: 500
# Notably, Echo can't read embedded art from ogg files.

lrc_lyrics: omit
# Echo supports lrc lyrics, so let's save them.
# Unsynced lyrics however, can't be scrolled, so no point having them.

