# If you got here you already know how to do the server configuration.

####
# This here is my profile for a FIIO Snowsky Echo,
# audiophile mode, i.e. keep as much quality as possible,
# but transcode the songs that the Echo can't play.
#
# This also happens to illustrate every feature I needed
# to program in to support every quirk of this device.

[echo]
default: no
# Normally, you want this to be where your SD card
# is mounted and work directly with it.
music_dir: testdir/ECHO_SD

# The list of supported formats for FIIO Echo is not very long.
# * While Wma files are theoretically supported,
#   the metadata situation with them is super dubious,
#   so the few that I do have are better off transcoded.
# * Ogg files work sporadically and cannot be relied on,
#   so they need to be transcoded too.
# * Mp3 files need to have ID3v2.3 UTF-16 tags, rather
#   than the more modern ID3v2.4 UTF-8 tags.
#   This will be handled separately later.
# * AIFF files are not supported by the player.
# * WAV might be supported, but is a senseless
#   travesty, don't do that, use flac or m4a-alac or ape...
supported_formats: mp3,m4a,aac,flac,ape,dsf,dff

# Losslessly encoded files, unless you encode them for bats,
# will not exceed an effective bitrate of 1500, thus ensuring
# that anything Echo can play at all will be downloaded
# as is, while everything it can't play will become ogg.
# Some bandcamp artists like to distribute their files
# as 24bit/96khz, i.e for bats, making 3000kbit the real
# cutoff if you want to keep them as is.
max_bitrate: 3000

# Contrary to all reason, Echo does not read per-folder
# cover art, but reads embedded cover art.
# (Unlike Echo Mini.)
#
# Thus it is important that your conversion process
# embeds cover art properly and that your source files
# already have embedded cover art in sane formats
# (Echo only supports jpg) and sizes (apparently anything
# bigger than ~1000 pixels is a no go).
#
# Ensuring compliance can be taken care of with the
# postprocessor, see below.
coverart: no

# Echo can scroll timed lyrics, but won't be able to do
# much with untimed lyrics.
lrc_lyrics: omit

# The meat of the procedure: Transcoding the things Echo
# can't play.
#
# When you have to transcode music to a lossy format at
# all, (and unwrapping everything to flac is kinda silly,
# when your source is already lossy) vorbis-in-ogg is
# theoretically the best lossy target FIIO Echo supports.
# In practice, ogg support is actually very broken, half
# the resulting ogg files don't work for no rhyme nor reason.
# The next best codec is AAC.
#
# Navidrome unfortunately can't cleanly produce a streamable
# m4a file, and un-containered raw AAC streams can't have metadata.
# Which is why we're going to download the source file and do
# the transcoding locally.
#
# The local_transcoder parameter configures a command that will
# transcode a {from} file (which is what we download off the server
# to a {to} file, (which is what goes to the Echo).
# This will be done instead of streaming whatever Navidrome
# generates and saving that.
#
# The 'format' parameter is then assumed to be the format extension
# for the result. 
format: m4a
bitrate: 320
# Keep in mind that Navidrome interprets the "bitrate" here as
# a maximum bitrate, and can and will drag it down as it likes,
# with no easily explainable logic. Your script will directly
# receive the bitrate you specify here.
#
# For your sanity, do use a script, instead of trying to produce
# a command line that fits in here.
local_transcoder: """scripts/m4a.sh "{from}" "{to}" "{bitrate}""""
# My script, produced after much mucking around, is included.
# It is unfortunately not cross-platform as such, but only
# requires ffmpeg, so there's hope someone clever will translate it.

# Echo has one other exotic requirements: embedded covers in mp3 files
# will only work if they contain IDv2.3 tags, not IDv2.4.
#
# This necessitates a postprocessing step for otherwise normal mp3s,
# if your library, like mine, has those throughout.
#
# This script will be run for all downloaded files that do not get transcoded,
# and is expected to turn {from} into {to}.
#
# It is assumed it will determine what, if any, postprocessing will be
# required.
postprocessor: """scripts/fix-mp3-idv3.sh "{from}" "{to}""""

# In all cases, pseudosonic will take care of deleting the {from}
# and ignore errors when doing so.

