# If you got here you already know how to do the server configuration.

####
# This here is my profile for a FIIO Snowsky Echo,
# audiophile mode, i.e. keep as much quality as possible,
# but transcode the songs that the Echo can't play.
#
# This also happens to illustrate every feature I needed
# to program in to support every quirk of this device.
#
# Despite the similarities of Echo Mini, it has
# entirely different firmware bugs, so cross-pollinate
# with a grain of salt.

[echo]
default: no
# Normally, you want this to be where your SD card
# is mounted and work directly with it.
music_dir: testdir/ECHO_SD

# The list of supported formats for FIIO Echo is not very long.
# * While WMA files are theoretically supported,
#   the metadata situation with them is super dubious,
#   so the few that I do have are better off transcoded.
# * OGG files work sporadically and cannot be relied on,
#   so they need to be transcoded too.
# * MP3 files need to have ID3v2.3 UTF-16 tags, rather
#   than the more modern ID3v2.4 UTF-8 tags.
#   This will be handled separately later.
# * AIFF files are not supported by the player.
# * WAV might be supported, but is a senseless
#   travesty, don't do that, use flac or m4a-alac or ape...
supported_formats: mp3,m4a,aac,flac,ape,dsf,dff

# Losslessly encoded files, unless you encode them for bats,
# will not exceed an effective bitrate of 1500, thus ensuring
# that anything Echo can play at all will be downloaded
# as is, while everything it can't play will be transcoded.
# Some Bandcamp artists like to distribute their files
# as 24bit/96khz, i.e for bats, making 3000kbit the real
# cutoff if you want to keep them as is.
# 
# Echo officially does not support sample rates higher 
# than 192k, but honestly, anything much over 48k is
# excessive. 24bits can be quite important, though.
#
# If you still wish to keep everything up to
# the maximum nominally supported, set the limit at
# 6000, which is generously above average for a 
# 24/192 lossless.
#
max_bitrate: 3000

# Contrary to all reason, Echo does not read per-folder
# cover art, but reads embedded cover art.
#
# (Unlike Echo Mini, which at least claims to read
# per-folder cover art in the manufacturer's FAQ.)
#
# Thus it is important that your conversion process
# embeds cover art properly and that your source files
# already have embedded cover art in sane formats
# (Echo only supports jpg) and sizes (apparently anything
# bigger than ~1000 pixels is a no go).
#
# With Navidrome specifically, I find it convenient to
# produce (via script) a special cover.jpg optimized for
# embedding (scaled down to about 500x500) and move the
# un-optimized nice image to cover-original.jpg,
# which is then given priority for Navidrome to show
# and return to players that actually request it via API.
# Musicbrains Picard is then configured to embed that
# optimized cover.jpg as part of my half-yearly data
# update cycle.
#
# I have yet to see Echo fail to display non-square cover
# art, when this is reported to be a problem for Mini.
# Sometimes, it displays garbage lines around it, but
# this has never caused a more serious problem.
#
# Ensuring compliance can be taken care of with the
# postprocessor, (see below) but the script supplied
# in this example does not actually do that.
coverart: no

# Echo can scroll synchronized lyrics, but won't be able to do
# much with untimed lyrics. So we write out timed lyrics
# to LRC files and ignore untimed lyrics.
# Echo actively dislikes embedded untimed lyrics, too.
lrc_lyrics: omit

# The meat of the procedure: Transcoding the things Echo
# can't play.
#
# When you have to transcode music to a lossy format at
# all, (and unwrapping everything to FLAC is kinda silly,
# when your source is already lossy) Vorbis-in-Ogg is
# theoretically the best lossy target FIIO Echo supports.
#
# In practice, OGG support is actually very broken, half
# the resulting files don't work for no rhyme nor reason.
# The next best usable codec, transparency-to-bitrate, is AAC.
#
# Navidrome unfortunately can't cleanly produce a streamable
# M4A file, and un-containered raw AAC streams can't have metadata.
# Which is why we're going to download the source file and do
# the transcoding locally.
#
# The local_transcoder parameter configures a command that will
# transcode a {from} file (which is what we download off the server)
# to a {to} file, (which is what goes to the Echo).
# This will be done instead of streaming whatever Navidrome
# generates and saving that.
#
# The 'format' parameter is then assumed to be the format extension
# for the result. 
format: m4a
bitrate: 320
# Keep in mind that Navidrome interprets the "bitrate" here as
# a maximum bitrate, and can and will drag it down as it likes,
# with no easily explainable logic. Your script will directly
# receive the bitrate you specify here.
#
# For your sanity, do use a script, instead of trying to produce
# a command line that fits in here.
local_transcoder: """scripts/m4a.sh "{from}" "{to}" "{bitrate}""""
# My script, produced after much mucking around, is included.
# It is unfortunately not cross-platform as such, but only
# requires ffmpeg, so there's hope someone clever will translate it,
# or sic enough Claude on it to get it working.

# Echo has one other exotic requirements: embedded covers in mp3 files
# will only work if they contain ID3v2.3 tags, not ID3v2.4.
# ID3v2.4 tags might be responsible for other observed issues.
# And it also doesn't like embedded lyrics and will randomly
# refuse to play some files that have them, but not all.
#
# This necessitates a postprocessing step for otherwise normal mp3s,
# if your library, like mine, has those throughout. Which is the
# default if you process it with Musicbrainz Picard.
#
# This script will be run for all downloaded files that do not get transcoded,
# and is expected to turn {from} into {to}.
#
# It is assumed it will determine what, if any, postprocessing will be
# required.
postprocessor: """scripts/postprocess.sh "{from}" "{to}""""

# In all cases, pseudosonic will take care of deleting the {from}
# and ignore errors when doing so.

